# this goes inside _config.yml. Change as required
home:
        - text: CIS 7000 - Large Language Models
          url: /index.html
navigation:
        - text: Syllabus
          url: /syllabus.html
        - text: Schedule
          url: /schedule.html
        - text: Homeworks
          url: /homeworks.html
        - text: Calendar
          url: /calendar.html
        - text: Staff
          url: /staff.html
