title: "CIS 7000 - LLMs"
baseurl: "https://llm-class.github.io"
navigation:
       - name: Syllabus
         link: /syllabus.html
       - name: Speakers
         link: /speakers.html
       - name: Schedule
         link: /schedule.html
       - name: Homeworks
         link: /homeworks.html
       - name: Calendar
         link: /calendar.html
       - name: Staff
         link: /staff.html
       - name: Sponsor
         link: /sponsor.html
markdown: kramdown
